import React from "react";
import { GetStaticPaths, GetStaticProps } from "next";
import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { GetServerSideProps } from "next/types";

const URL = `https://yesno.wtf/api`;

type Data = {
  answer: string;
  forced: boolean;
  image: string;
};

type PathParams = {
  id: string;
};

type PageProps = {
  id: string;
  data: Data;
};

export const getStaticPaths: GetStaticPaths<PathParams> = async () => {
  const paths = [{ params: { id: "ssg1" } }, { params: { id: "ssg2" } }];
  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps: GetStaticProps<PageProps> = async (context) => {
  const { id } = context.params as PathParams;
  const res = await axios.get<Data>(URL);
  const props: PageProps = {
    id,
    data: res.data,
  };

  return { props };
};

// ページコンポーネントの実装
const Ids: React.FC<PageProps> = ({ id, data }: PageProps) => {
  const { answer, forced, image } = data;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>SSG {id}ページ</h1>
        <p>
          YesかNoで答えてくれるAPI １万回に１回、maybeが返ることもあるらしい。
        </p>
        <p>{answer}</p>
        <Image src={image} width={300} height={300} alt="logo" />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};
export default Ids;
