import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { GetServerSideProps } from "next/types";
import axios from "axios";

const URL = `https://yesno.wtf/api`;

type Data = {
  answer: string;
  forced: boolean;
  image: string;
};

type Props = {
  data: Data;
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const res = await axios.get<Data>(URL);
  const data = res.status === 200 ? res.data : undefined;
  return {
    props: {
      data,
    } as Props,
  };
};

export default function Ssr({ data }: Props) {
  const { answer, forced, image } = data;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>SSR</h1>
        <p>
          YesかNoで答えてくれるAPI １万回に１回、maybeが返ることもあるらしい。
        </p>
        <p>{answer}</p>
        <Image src={image} width={300} height={300} alt="logo" />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
